### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by Filipoda123** [Endermanch/scripts#1]
What's the import for the Cryptodome library? When I try to get pycrypto, it fails to build its wheel

**Comment by NeoNyaa** [comment]
> What's the import for the Cryptodome library? When I try to get pycrypto, it fails to build its wheel

If I am not mistaken you are looking for the [pycryptodome](https://github.com/Legrandin/pycryptodome) package, you can install it with the following command: `pip install pycryptodome`

**Comment by dddaniel13** [comment]
> What's the import for the Cryptodome library? When I try to get pycrypto, it fails to build its wheel

`pip install pycryptodomex` i think

**Comment by Filipoda123** [comment]
Thank you! When using pycryptodome u have to change Cryptodome to Crypto in the imports though, love yall

**Comment by Endermanch** [comment]
> > What's the import for the Cryptodome library? When I try to get pycrypto, it fails to build its wheel
> 
> `pip install pycryptodomex` i think

You're correct. I used Pycryptodomex, because it is the preferred way of using the Cryptodome library, and the one without an X is left there for legacy reasons. @depau added the requirements file to avoid confusion in #3.
