### ISSUE TITLE
import fd2dt from sam.utils

### ISSUE THREAD

**Issue by IvoAndre** [Endermanch/scripts#2]
I installed all the modules that the script asked for including 'sam[all]' but when running it gives me the following error:

Traceback (most recent call last):
  File "C:\Users\[username]\Desktop\samreader\samreader.py", line 13, in <module>
    from sam.utils import ft2dt
ImportError: cannot import name 'ft2dt' from 'sam.utils' (C:\Users\[username]\AppData\Roaming\Python\Python312\site-packages\sam\utils\__init__.py)

I've searched far and wide and didn't find anything about this.
Any support would be appreciated.

**Comment by KingGamingYT** [comment]
I have no idea if this is the correct solution but since the repo already has utils.py I just removed "sam" so it imports from utils.py in the same file directory

**Comment by IvoAndre** [comment]
Thanks 

> I have no idea if this is the correct solution but since the repo already has utils.py I just removed "sam." so it imports from utils.py in the same file directory

That seems to have worked, thanks for the help.

**Comment by Endermanch** [comment]
Fixed in 5a37677 to avoid confusion.
